#!/bin/bash

# must edit
CLUSTER_NAME="demo1"

# optional config
export CLUSTER_REGION="us-west1"
export CLUSTER_ZONE="${CLUSTER_REGION}-a"
export CLUSTER_NODE_MACHINE_TYPE="n1-standard-4"
export CLUSTER_RELEASE_CHANNEL="regular"

# derived values
export PROJECT_ID=$(gcloud config get-value project)
export CURRENT_ACCOUNT=$(gcloud config get-value account)
export SERVICE_ACCOUNT="${CLUSTER_NAME}-sa"