#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# deploy test app
kubectl apply -f cr-test.yaml

echo "Test app deployed. Will now check pod STATUS"
echo "Use CTRL-C when STATUS reads 'Running'"
read -p "Press enter to start the check..."
watch kubectl get pods -n demo

echo "Check the deployed service in browser"
read -p "Press enter to launched the test app..."
open "https://test.demo.${CUSTOM_DOMAIN}"