#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

gcloud run deploy "test" \
    --image "gcr.io/cloudylabs-public/maxprime:0.2.1"
    --platform gke \
    --cluster $CLUSTER_NAME \
    --cluster-location $CLUSTER_ZONE \
    --namespace demo \
    --args "RELEASE=v0.2.1-simple"

read -p "Press enter to navigate to the test service (https://test.demo.${CUSTOM_DOMAIN})"
open "https://test.demo.${CUSTOM_DOMAIN}"